facebook_username = "Arkoprabho Das"
facebook_password = "Arko1234#"
pinterest_email = "arkoprabho900@gmail.com"
pinterest_password = "Arko1234#"
uri = "mongodb+srv://arkoprabho12:Arko1234#@arko0.r2kihyv.mongodb.net/ArkoDB?retryWrites=true&w=majority"
database_name = "ArkoDB"
collection_name = "Users"